# Generated by Django 5.0.2 on 2024-02-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="goldModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=30)),
                ("lname", models.CharField(max_length=30)),
                ("dob", models.DateField()),
                ("mobile", models.CharField(max_length=30)),
                ("address", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="PlatinumModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=30)),
                ("lname", models.CharField(max_length=30)),
                ("dob", models.DateField()),
                ("mobile", models.CharField(max_length=30)),
                ("address", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="silverModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=30)),
                ("lname", models.CharField(max_length=30)),
                ("dob", models.DateField()),
                ("mobile", models.CharField(max_length=30)),
                ("address", models.CharField(max_length=30)),
            ],
        ),
    ]
